# -*- coding: utf-8 -*-
'''
FSECplotter2 - The interactive plotting application for FSEC.

Copyright 2015-2016, TaizoAyase, tikuta, biochem-fan

This file is part of FSECplotter2.

FSECplotter2 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

# Form implementation generated from reading ui file 'preference_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferenceDialog(object):
    def setupUi(self, PreferenceDialog):
        PreferenceDialog.setObjectName("PreferenceDialog")
        PreferenceDialog.resize(430, 500)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(PreferenceDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(PreferenceDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.default_tab = QtWidgets.QWidget()
        self.default_tab.setObjectName("default_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.default_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.detector_channel_group = QtWidgets.QGroupBox(self.default_tab)
        self.detector_channel_group.setObjectName("detector_channel_group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.detector_channel_group)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.detector_channel_group)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.detector_comboBox = QtWidgets.QComboBox(self.detector_channel_group)
        self.detector_comboBox.setCurrentText("B")
        self.detector_comboBox.setObjectName("detector_comboBox")
        self.detector_comboBox.addItem("")
        self.detector_comboBox.setItemText(0, "A")
        self.detector_comboBox.addItem("")
        self.detector_comboBox.setItemText(1, "B")
        self.horizontalLayout.addWidget(self.detector_comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.detector_channel_group)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.channel_spinBox = QtWidgets.QSpinBox(self.detector_channel_group)
        self.channel_spinBox.setMaximum(10)
        self.channel_spinBox.setProperty("value", 1)
        self.channel_spinBox.setObjectName("channel_spinBox")
        self.horizontalLayout_2.addWidget(self.channel_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.detector_channel_group)
        self.flowrate_group = QtWidgets.QGroupBox(self.default_tab)
        self.flowrate_group.setObjectName("flowrate_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.flowrate_group)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.flowrate_group)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.flowrate_group)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.flowrate_spinBox = QtWidgets.QDoubleSpinBox(self.flowrate_group)
        self.flowrate_spinBox.setDecimals(2)
        self.flowrate_spinBox.setMaximum(25.0)
        self.flowrate_spinBox.setProperty("value", 10.0)
        self.flowrate_spinBox.setObjectName("flowrate_spinBox")
        self.horizontalLayout_5.addWidget(self.flowrate_spinBox)
        self.label_8 = QtWidgets.QLabel(self.flowrate_group)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_5.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.flowrate_group)
        self.plot_params = QtWidgets.QGroupBox(self.default_tab)
        self.plot_params.setObjectName("plot_params")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.plot_params)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.plot_params)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.linewidth_spinBox = QtWidgets.QDoubleSpinBox(self.plot_params)
        self.linewidth_spinBox.setDecimals(1)
        self.linewidth_spinBox.setSingleStep(0.5)
        self.linewidth_spinBox.setProperty("value", 1.0)
        self.linewidth_spinBox.setObjectName("linewidth_spinBox")
        self.horizontalLayout_6.addWidget(self.linewidth_spinBox)
        self.label_10 = QtWidgets.QLabel(self.plot_params)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.plot_params)
        spacerItem = QtWidgets.QSpacerItem(20, 157, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.default_tab, "")
        self.advanced_tab = QtWidgets.QWidget()
        self.advanced_tab.setEnabled(True)
        self.advanced_tab.setObjectName("advanced_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.advanced_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ts_group = QtWidgets.QGroupBox(self.advanced_tab)
        self.ts_group.setObjectName("ts_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ts_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.ts_group)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.ts_group)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.ts_gain_lineEdit = QtWidgets.QLineEdit(self.ts_group)
        self.ts_gain_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ts_gain_lineEdit.setClearButtonEnabled(False)
        self.ts_gain_lineEdit.setObjectName("ts_gain_lineEdit")
        self.horizontalLayout_3.addWidget(self.ts_gain_lineEdit)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.ts_group)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.ts_tm_lineEdit = QtWidgets.QLineEdit(self.ts_group)
        self.ts_tm_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ts_tm_lineEdit.setObjectName("ts_tm_lineEdit")
        self.horizontalLayout_4.addWidget(self.ts_tm_lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.ts_group)
        spacerItem3 = QtWidgets.QSpacerItem(20, 238, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.tabWidget.addTab(self.advanced_tab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferenceDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_6.addWidget(self.buttonBox)
        self.label.setBuddy(self.detector_comboBox)
        self.label_2.setBuddy(self.channel_spinBox)
        self.label_7.setBuddy(self.flowrate_spinBox)
        self.label_9.setBuddy(self.linewidth_spinBox)
        self.label_3.setBuddy(self.ts_gain_lineEdit)
        self.label_4.setBuddy(self.ts_tm_lineEdit)

        self.retranslateUi(PreferenceDialog)
        self.tabWidget.setCurrentIndex(0)
        self.detector_comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PreferenceDialog)

    def retranslateUi(self, PreferenceDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferenceDialog.setWindowTitle(_translate("PreferenceDialog", "Preferences"))
        self.detector_channel_group.setTitle(_translate("PreferenceDialog", "Detector / Channel parameters"))
        self.label.setText(_translate("PreferenceDialog", "Default Detector:"))
        self.label_2.setText(_translate("PreferenceDialog", "Default Channel:"))
        self.flowrate_group.setTitle(_translate("PreferenceDialog", "Flow rate"))
        self.label_6.setText(_translate("PreferenceDialog", "Default value when failed to get flow rate from logfile."))
        self.label_7.setText(_translate("PreferenceDialog", "Default flow rate:"))
        self.label_8.setText(_translate("PreferenceDialog", "mL/min"))
        self.plot_params.setTitle(_translate("PreferenceDialog", "Plot params"))
        self.label_9.setText(_translate("PreferenceDialog", "Default line width:"))
        self.label_10.setText(_translate("PreferenceDialog", "pt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.default_tab), _translate("PreferenceDialog", "Default Parameters"))
        self.ts_group.setTitle(_translate("PreferenceDialog", "FSEC-TS parameter"))
        self.label_5.setText(_translate("PreferenceDialog", "Initial value for curve sigmoid fitting of FSEC-TS tool. "))
        self.label_3.setText(_translate("PreferenceDialog", "Gain:"))
        self.ts_gain_lineEdit.setText(_translate("PreferenceDialog", "1.0"))
        self.label_4.setText(_translate("PreferenceDialog", "Tm:  "))
        self.ts_tm_lineEdit.setText(_translate("PreferenceDialog", "50"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.advanced_tab), _translate("PreferenceDialog", "Advanced"))

